apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-api
  labels:
    app: metrics-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metrics-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: metrics-api
    spec:
      containers:
      - name: metrics-api
        image: yuvraaj14/ecommerce-pipeline:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: pipeline-secrets
              key: redis-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-api-service
spec:
  selector:
    app: metrics-api
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer