apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secrets
type: Opaque
stringData:
  redis-url: "rediss://default:gQAAAAAAAdSLAAIgcDJiODQ3YWJkZTg2NTY0ZGE5YTc2ODVhZDVhYTBlYTE0Yg@rare-ape-119947.upstash.io:6379"
  supabase-password: "Yuvraaj142002@"